### ISSUE TITLE
error when making changes to the user profile

### ISSUE THREAD

**Issue by roxannewyns** [libis/Espace#11]
assigned @naeemmuhammad 

I added address (Leuven) and gender (female) to my profile and received the following error. The changes where registered however. 

![espace3](https://cloud.githubusercontent.com/assets/3798589/7878580/546681e4-05e8-11e5-9885-b20c454f28a6.JPG)

**Comment by naeemmuhammad** [comment]
Could not reproduce this error, profile adding/editing/deleting seems to be working fine now.
