### ISSUE TITLE
change exhibit / exhibits into story / stories

### ISSUE THREAD

**Issue by roxannewyns** [libis/Espace#13]
assigned @JorisLambrechts 

Can you change exhibit / exhibits into story / stories in the CSS?

![espace5](https://cloud.githubusercontent.com/assets/3798589/7878764/2c501024-05ea-11e5-82d2-8bfabe109f9e.JPG)

**Comment by JorisLambrechts** [comment]
Not really, there is no way to select something base on the content. So Exhibits would have to be wrapped in a div or span with a class or id, but this is not the case. So this will have to be done in the code (or maybe in the language files).
