### ISSUE TITLE
no option to put item to public

### ISSUE THREAD

**Issue by roxannewyns** [libis/Espace#16]
assigned @JorisLambrechts 
cc @naeemmuhammad 

At the moment there is no option to put an item as 'Public'. 

![espace9](https://cloud.githubusercontent.com/assets/3798589/7879172/51def0f4-05ee-11e5-956b-3d46ebc0c830.JPG)

**Comment by roxannewyns** [comment]
can the default for items be public?

**Comment by JorisLambrechts** [comment]
Normally you have 2 check boxes under de delete button on the right: public yes/no and featured yes/no.

Public is set to yes by default.

I'm logged in a super user though.

**Comment by naeemmuhammad** [comment]
commit: bb27c501697e31cc0373f0aa08711e249714aa6f
