### ISSUE TITLE
thumbnail groter

### ISSUE THREAD

**Issue by roxannewyns** [libis/Espace#17]
assigned @JorisLambrechts 

kan de thubnail in een verhaal wat groter?
![capture](https://cloud.githubusercontent.com/assets/3798589/7879596/fb8c3e38-05f1-11e5-9d08-3d7a0f45a286.JPG)

**Comment by JorisLambrechts** [comment]
Tijdens het aanmaken of editeren van een pagina kan je via de tab 'layout options' (onder text-blok) kiezen welke afbeeldingsgrootte je pakt (thumbnail, square thumbnail of full). Als je full pakt wordt heel de ruimte gebruikt. 

Via appearance->settings kan de grootte van een thumbnail etc (alle thumbnails over heel de site) gekozen worden.

**Comment by roxannewyns** [comment]
Dat van settings weet ik, maar bij aanpasse van 200 naar 500 pixels als test zie geen verschil.

**Comment by roxannewyns** [comment]
als ik de settings aanpas blijven de afbeeldingen even groot.

**Comment by JorisLambrechts** [comment]
in het voorbeeld, is een gallery geselecteerd, dan zijn de afbeeldingen kleiner maar worden er meer getoond alleen is er in dit geval maar één waardoor het er wat raar uit ziet. Indien er maar één afbeelding is pak je beter 'file and text' ipv 'gallery' dan is de afbeelding groter.
