### ISSUE TITLE
add home button

### ISSUE THREAD

**Issue by roxannewyns** [libis/Espace#18]
assigned @JorisLambrechts 

add a Home button 
![capture](https://cloud.githubusercontent.com/assets/3798589/7881438/364fafee-0603-11e5-9c71-a22c10913892.JPG)

**Comment by JorisLambrechts** [comment]
is this the right screenshot?

**Comment by roxannewyns** [comment]
nee, mij vergist bij opladen, gewoon in bovenhoek zetten in navigatiebalk is ok

**Comment by roxannewyns** [comment]
in orde
