### ISSUE TITLE
provide link to my account from back-end

### ISSUE THREAD

**Issue by roxannewyns** [libis/Espace#19]
assigned @naeemmuhammad 
cc @JorisLambrechts 

at the moment there is no link back to the My account page (espace_test/guest-user/user/me)
Can you put this behind My dashboard?

![capture](https://cloud.githubusercontent.com/assets/3798589/7881796/0e1d8272-0607-11e5-8953-503dc5417ae2.JPG)

**Comment by naeemmuhammad** [comment]
commit: d0cba42703666c8abdfb23fc3034d53402bea0bf
