### ISSUE TITLE
Show Display name instead of user role

### ISSUE THREAD

**Issue by roxannewyns** [libis/Espace#2]
assigned @naeemmuhammad 
For espace_test

Show the users 'Display name' instead of the role

![capture](https://cloud.githubusercontent.com/assets/3798589/7347913/5fcefdfe-eced-11e4-9e84-c935543beb15.JPG)

**Comment by naeemmuhammad** [comment]
We hide Omeka Admin from the menu bar because users will move to the admin part via links from their account dash boards.
