### ISSUE TITLE
browse stories overzicht organiseren

### ISSUE THREAD

**Issue by roxannewyns** [libis/Espace#21]
assigned @JorisLambrechts 

De browse stories resultaten pagina is nogal chaotisch. Kan je dat reorganiseren. 
Er kan best ook nog een simple search veld toegevoegd worden aan deze pagina. 

![capture](https://cloud.githubusercontent.com/assets/3798589/9246901/469d8c3a-41af-11e5-9354-bbf8da4d7170.JPG)

**Comment by JorisLambrechts** [comment]
https://github.com/libis/Espace/commit/a6d622eefd390936d7387d671393a5565c807a92
https://github.com/libis/Espace/commit/fdede90ff857493816cb1ee2ad2f4c44f7462134
