### ISSUE TITLE
design

### ISSUE THREAD

**Issue by roxannewyns** [libis/Espace#26]
assigned @JorisLambrechts 

langere titels plakken beetje tegen elkaar

![capture](https://cloud.githubusercontent.com/assets/3798589/9249698/beae4b98-41c7-11e5-84f1-984b91e63b94.JPG)

**Comment by roxannewyns** [comment]
tekst niet leesbaar
![capture](https://cloud.githubusercontent.com/assets/3798589/9249887/2db7219e-41c9-11e5-8476-81743b0ccd61.JPG)

**Comment by JorisLambrechts** [comment]
https://github.com/libis/Espace/commit/7f1084da673e761a033148d0377f632028ddfbe3
