### ISSUE TITLE
hide search form element

### ISSUE THREAD

**Issue by roxannewyns** [libis/Espace#27]
assigned @JorisLambrechts 

To make the search for easier for the end users, it would be helpfull to hide some search options 

HIDE/Remove:

Search by a range of ID#s (example: 1-4, 156, 79) 
Search by type
Featured/Non-Featured
Geographic Address
Geographic Radius (miles)

**Comment by roxannewyns** [comment]
waar is dit juist gedaan, want ik zie ze nog steeds, zowel front #32 als back-end
![capture](https://cloud.githubusercontent.com/assets/3798589/10247874/4bdf4492-691c-11e5-8b16-1a04d5a34518.JPG)

**Comment by JorisLambrechts** [comment]
https://github.com/libis/Espace/commit/cad4176bf4010e2a48abcbc43ae6b1b25c404cc3
