### ISSUE TITLE
add / edit profile picture

### ISSUE THREAD

**Issue by roxannewyns** [libis/Espace#28]
assigned @naeemmuhammad 

can't find where to edit my picture. Now some icon appears on the comment I made

![capture](https://cloud.githubusercontent.com/assets/3798589/9250689/521bf22a-41cf-11e5-9f38-de7aa99d53c3.JPG)

**Comment by naeemmuhammad** [comment]
As i once demonstrated you that this image comes from an external website. You wanted to test it yourself before deciding on it. Should it be closed or we need to implement this feature?

**Comment by roxannewyns** [comment]
no need for now
