### ISSUE TITLE
Filter user's own items

### ISSUE THREAD

**Issue by naeemmuhammad** [libis/Espace#29]
User should be able to filter its own items from others.

**Comment by naeemmuhammad** [comment]
User can now filter items by selecting 'own' in 'Quick Filter' list. This filter only shows public/private items of the current user.  Also, by default items are filtered for 'own'. User can use other filters to see public items from other users.

**Comment by roxannewyns** [comment]
The filter works fine for items, but the default setting isn't 'own'. When I log in and go to My items, I see all items from all users and have to set the quick filter to 'own' to see the change.

Also, the same filter has to be applied for Stories and Collections, so users van easily filter on own stories and own collections (again the default setting) and all stories and all collections

**Comment by roxannewyns** [comment]
the same kind of filter should be available for the item search for in exhibits. Default should be that you only see your own items
![capture](https://cloud.githubusercontent.com/assets/3798589/10247934/ae922050-691c-11e5-865e-7037a72ceaa6.JPG)
