### ISSUE TITLE
User profile (/user-profiles/profiles/)

### ISSUE THREAD

**Issue by roxannewyns** [libis/Espace#3]
For espace_test

assigned @naeemmuhammad 
Metadata is ok for now. Just add another check box for gender 'Leave blank'. 

First name
Last name
Gender: 
    Male 
    Female
    Leave blank
Country
Address

Add a back button to the dashboard. We can call it. "Back 2 My Space", or "My Space", or "Dashboard". 

@JorisLambrechts Design of /user-profiles/profiles/
- Don't show the add input fields
- Make the fields a bit smaller so the user has an immediate view of the metadata 
- Remove 'Use HTML'
  ![capture](https://cloud.githubusercontent.com/assets/3798589/7348187/b815a90c-ecef-11e4-96a9-23ab4079cb48.JPG)

This should show the users "Display name". 
![capture](https://cloud.githubusercontent.com/assets/3798589/7348108/f6365a66-ecee-11e4-9ac8-c652ca7f34e6.JPG)

(Good example velehanden.nl/account/gebruiker/aanmelden)

**Comment by naeemmuhammad** [comment]
A new menu item 'Europeana Dashboard' has been added to the admin menu to allow users to go back to the 'My Account' section.
commit: d0cba42703666c8abdfb23fc3034d53402bea0bf

**Comment by roxannewyns** [comment]
perhaps better to rename "ESpace Dashboard" into 'My Space' since its more consistent in terminology and there is a specific difference with the other Dashboard tab. 

![capture](https://cloud.githubusercontent.com/assets/3798589/9248101/4b7a071a-41b9-11e5-843c-685ca7444a33.JPG)
![capture](https://cloud.githubusercontent.com/assets/3798589/9248139/aae11fcc-41b9-11e5-8b68-1ce20ea2647c.JPG)

After that this issue can be closed. The other things are details and if required we can deal with them later on.
