### ISSUE TITLE
search Items

### ISSUE THREAD

**Issue by roxannewyns** [libis/Espace#32]
assigned @JorisLambrechts 

*
zoekbox alligneren. de tekst die er in staat is toch niet leesbaar. misschien beter een help tekst toevoegen ernaast die we met simple page kunnen aanvullen. ook voor de andere search pagina's (items, collections, stories)

![capture](https://cloud.githubusercontent.com/assets/3798589/10246895/5238619a-6915-11e5-9a4e-ba1bd5b589a1.JPG)

*
kan je de positie van de kaart op Europa zetten. staat nu op VS

*
Advanced search velden inkorten:
- Search for keywords
- Search for specific fields --> kan je hier enkel die DC velden laten verschijnen die in gebruik zijn door toegevoegde items, want nu nogal een lange lijst? Indien niet, dan geef ik een verkorte lijst door.
- Search by collection
- search by user
- Search by tag
- Search by exhibit

**Comment by JorisLambrechts** [comment]
"Search for specific fields --> kan je hier enkel die DC velden laten verschijnen die in gebruik zijn door toegevoegde items, want nu nogal een lange lijst? Indien niet, dan geef ik een verkorte lijst door."

Dit is makkelijker met een lijst, anders moet er in de core geprutst worden

**Comment by JorisLambrechts** [comment]
alles in orde buiten de lijst
