### ISSUE TITLE
create your own story

### ISSUE THREAD

**Issue by roxannewyns** [libis/Espace#34]
'Create your own story' (roze kader) en 'Get started' (in banner home page) laten doorverwijzen naar /espace_test/create-your-own-story. Hier komt de info in stappen van hoe ze zelf een verhaal kunnen maken. 

Sub navigatiebalk toevoegen (bij alle simple pages, zodat er ook een sub navigatiebalk langs de zijkant verschijnt bij "About the photography pilot")

nu verschijnt er op de simple pages altijd het kader 'Create your own story'. Ook deze moet doorverwijzen naar de simple page /espace_test/create-your-own-story . Wel beetje raar dat het kader daar ook verschijnt, maar ik vermoed dat je dat niet kan aanpassen? 

Je mag een foto nemen uit de collectie /collections/show/4 als foto voor het roze kader 
![capture](https://cloud.githubusercontent.com/assets/3798589/10247586/6777bcea-691a-11e5-8ec6-c485fdde9820.JPG)

**Comment by JorisLambrechts** [comment]
d515586dae1d1bb3b04e9ceb2c16b8f042aa00fe
