### ISSUE TITLE
searching items using europeana space api gives error

### ISSUE THREAD

**Issue by roxannewyns** [libis/Espace#39]
![capture](https://cloud.githubusercontent.com/assets/3798589/10601994/fb70b858-7715-11e5-9b62-5ae78ea6ccad.JPG)

**Comment by naeemmuhammad** [comment]
This error is caused when no proxy information is given on server. Proxy information is configurable now, which can be provided in the configuration section of the LibCo plugin (in admin view).
Fixed: cc79e6e11fb61c2d7542344dc07f4b37964293d1
