### ISSUE TITLE
Plug-ins to hide from users with role "contributor"

### ISSUE THREAD

**Issue by roxannewyns** [libis/Espace#4]
Item types
Tags
Image manager
User profiles I think as well since its a duplication of the My Space dashboard. Or this tab should link back to the My Space dashboard, but you already have this at the top of the list. 
Map
Comments can remain in case that only the users own comments or comment on his own items or stories are shown. 
Idem for contributed items. Should only show items for the user itself. Perhaps there should also be something like Shared items (requirement 3.5, but its a could so this can wait).

**Comment by roxannewyns** [comment]
@naeemmuhammad 
if by next week you update the new desing, can you also disable the plug-ins mentioned above please

**Comment by naeemmuhammad** [comment]
Image manager, User profiles, Guest user and Geo location (map) plugins can now be configured to show/hide from the navigation menu. 
Item types and Tags are part of the core omeka implementation therefore need a separate solution.

**Comment by roxannewyns** [comment]
item types still need to be hidden
![espace8](https://cloud.githubusercontent.com/assets/3798589/7879109/95f868f2-05ed-11e5-90cc-97cfc78f95a6.JPG)

**Comment by roxannewyns** [comment]
As a contributor you can't edit item types and tags, so you can leave them visible. It might be useful for users wanting more info on available tags, items types ect.
