### ISSUE TITLE
item search doesn't work properly

### ISSUE THREAD

**Issue by roxannewyns** [libis/Espace#42]
searching on "SAL" or "Leuven gives no result while there are items containing this term in the metadata. I haven't checked the indexing settings
There is also no back button when you wan"t to go back to the search page. 
![capture](https://cloud.githubusercontent.com/assets/3798589/11425447/52459930-9455-11e5-92b8-427b04095458.JPG)

**Comment by JorisLambrechts** [comment]
Background scripts in config.ini weren't set correctly which broke indexing:

the correct setting:
jobs.dispatcher.default = "Omeka_Job_Dispatcher_Adapter_Synchronous"
;jobs.dispatcher.longRunning = "Omeka_Job_Dispatcher_Adapter_BackgroundProcess"
jobs.dispatcher.longRunning = "Omeka_Job_Dispatcher_Adapter_Synchronous"

**Comment by JorisLambrechts** [comment]
SAL or USA don't work because simple search only works with words of 4 characters or more. It's a mysql setting so not sure if we can change this.

http://dev.mysql.com/doc/refman/5.0/en/fulltext-fine-tuning.html
