### ISSUE TITLE
Image not beig imported

### ISSUE THREAD

**Issue by naeemmuhammad** [libis/Espace#48]
For some records images are not imported. This is happening because remote server where we download images does not provide access to certain images. Mainly it is happening with records searched from WITHin source.
Example: http://www.tellyourphotostory.be/espace_test/exhibits/show/naturevsnurture/naturevsnurture

A possible solution to solve this issue could be to add following source code in the download module:
            $context = stream_context_create(array(
                'http' => array(
                    'method' => "GET",
                    "Connection: keep-alive",
                    "ignore_errors" => true,
                    "timeout" => 3,
                    'proxy'=>get_option('libco_server_proxy')
                )
            ));
It worked on my local development environment, but did not work on server (production). It needs to be investigated why it did not work on server.

**Comment by roxannewyns** [comment]
is this still an issue or is it fixed? please comment and close

**Comment by naeemmuhammad** [comment]
Images are being imported. It was a proxy issue and icts solved it.
