### ISSUE TITLE
banner kleiner maken

### ISSUE THREAD

**Issue by roxannewyns** [libis/Espace#49]
Kan je de banner wat kleiner maken. Fred Truyen vond hem toch wat te breed. 
![capture](https://cloud.githubusercontent.com/assets/3798589/20434840/06b9c60c-adaa-11e6-8720-4212900057b1.JPG)

**Comment by JorisLambrechts** [comment]
ik heb het voorlopig rechtstreeks op de server aangepast omdat er een cursus van espace bezig is en een deployment deze zou kunnen onderbreken
