### ISSUE TITLE
add CS Digital logo

### ISSUE THREAD

**Issue by roxannewyns** [libis/Espace#6]
@JorisLambrechts 

Kan je nog bijgevoegd logo toevoegen aan het nieuwe Europeana Space design.
![cs digital](https://cloud.githubusercontent.com/assets/3798589/7745597/bcc33170-ffac-11e4-8849-76e983be3d90.png)

**Comment by JorisLambrechts** [comment]
is in orde https://github.com/libis/Espace/commit/9a8272c8c3f54895b6f9c62ad322844420c0e522 (ook niet op tijd gedeployed)
